# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"+\n\x15GetApplicationRequest\x12\x12\n\nidentifier\x18\x01 \x01(\t\")\n\x16GetApplicationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Q\n\nDataCenter\x12\x43\n\x0eGetApplication\x12\x16.GetApplicationRequest\x1a\x17.GetApplicationResponse\"\x00\x62\x06proto3'
)




_GETAPPLICATIONREQUEST = _descriptor.Descriptor(
  name='GetApplicationRequest',
  full_name='GetApplicationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='GetApplicationRequest.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=57,
)


_GETAPPLICATIONRESPONSE = _descriptor.Descriptor(
  name='GetApplicationResponse',
  full_name='GetApplicationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='GetApplicationResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['GetApplicationRequest'] = _GETAPPLICATIONREQUEST
DESCRIPTOR.message_types_by_name['GetApplicationResponse'] = _GETAPPLICATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetApplicationRequest = _reflection.GeneratedProtocolMessageType('GetApplicationRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETAPPLICATIONREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:GetApplicationRequest)
  })
_sym_db.RegisterMessage(GetApplicationRequest)

GetApplicationResponse = _reflection.GeneratedProtocolMessageType('GetApplicationResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETAPPLICATIONRESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:GetApplicationResponse)
  })
_sym_db.RegisterMessage(GetApplicationResponse)



_DATACENTER = _descriptor.ServiceDescriptor(
  name='DataCenter',
  full_name='DataCenter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=102,
  serialized_end=183,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetApplication',
    full_name='DataCenter.GetApplication',
    index=0,
    containing_service=None,
    input_type=_GETAPPLICATIONREQUEST,
    output_type=_GETAPPLICATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATACENTER)

DESCRIPTOR.services_by_name['DataCenter'] = _DATACENTER

# @@protoc_insertion_point(module_scope)
