# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class DataCenterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetApplication = channel.unary_unary(
                '/DataCenter/GetApplication',
                request_serializer=data__pb2.GetApplicationRequest.SerializeToString,
                response_deserializer=data__pb2.GetApplicationResponse.FromString,
                )


class DataCenterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataCenterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApplication,
                    request_deserializer=data__pb2.GetApplicationRequest.FromString,
                    response_serializer=data__pb2.GetApplicationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataCenter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataCenter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataCenter/GetApplication',
            data__pb2.GetApplicationRequest.SerializeToString,
            data__pb2.GetApplicationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
